# Generated by Django 4.2.5 on 2023-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='registration_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
