# Generated by Django 4.2.6 on 2023-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment_fixed',
            table='patient_appointment',
        ),
    ]
