# Generated by Django 4.2.6 on 2023-10-18 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('patient', '0002_alter_appointment_fixed_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_fixed',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to='user.user'),
        ),
        migrations.AlterField(
            model_name='appointment_fixed',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to='patient.patient_profile'),
        ),
    ]
