# Generated by Django 4.2.5 on 2023-09-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_profile_registration_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_profile',
            old_name='registration_id',
            new_name='unique_id',
        ),
    ]
