# Generated by Django 4.2.6 on 2023-10-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_appointment_fixed_reason_for_visit_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient_profile',
            table='patient_profile',
        ),
        migrations.DeleteModel(
            name='Appointment_fixed',
        ),
    ]
