<<<<<<< HEAD
# Generated by Django 5.0 on 2023-12-14 17:04
=======
# Generated by Django 5.0 on 2023-12-27 07:21
>>>>>>> 0a0d8f532772ef8919a2217788d4c6179800016c

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('labtest', '0001_initial'),
        ('medicine', '0001_initial'),
        ('patient', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionForLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('cc', models.TextField(null=True, verbose_name='Chief Complain')),
                ('oe', models.TextField(null=True, verbose_name='On Examination')),
                ('dd', models.TextField(null=True, verbose_name='Differential Diagnosis')),
                ('ad', models.TextField(null=True, verbose_name='Advice')),
                ('tl', models.TextField(null=True, verbose_name='Treatment List')),
                ('pmh', models.TextField(null=True, verbose_name='Past Medical History')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrescriptionForLabTestCreated', to='user.user')),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to='doctor.doctorprofile')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrescriptionForLabTestModified', to='user.user')),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_name', to='patient.patientprofile')),
            ],
            options={
                'db_table': 'prescription_for_lab_test',
            },
        ),
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabTestPrescriptionCreated', to='user.user')),
                ('lab_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicine', to='labtest.labtest')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabTestPrescriptionModified', to='user.user')),
                ('lab_prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_lab', to='prescription.prescriptionforlabtest')),
            ],
            options={
                'db_table': 'lab_test_prescription',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionForMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('cc', models.TextField(null=True, verbose_name='Chief Complain')),
                ('oe', models.TextField(null=True, verbose_name='On Examination')),
                ('dd', models.TextField(null=True, verbose_name='Differential Diagnosis')),
                ('ad', models.TextField(null=True, verbose_name='Advice')),
                ('tl', models.TextField(null=True, verbose_name='Treatment List')),
                ('pmh', models.TextField(null=True, verbose_name='Past Medical History')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrescriptionForMedicineCreated', to='user.user')),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='doctor.doctorprofile')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrescriptionForMedicineModified', to='user.user')),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient.patientprofile')),
            ],
            options={
                'db_table': 'prescription_for_medicine',
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('frequency', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MedicinePrescriptionCreated', to='user.user')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='medicine.medicine')),
                ('medicine_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicineschedule')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MedicinePrescriptionModified', to='user.user')),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescription', to='prescription.prescriptionformedicine')),
            ],
            options={
                'db_table': 'medicine_prescription',
            },
        ),
    ]
