# Generated by Django 4.2.5 on 2023-09-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='labtest',
            table='lab_test',
        ),
        migrations.AlterModelTable(
            name='medicineschedule',
            table='medicine_schedule',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescription',
        ),
        migrations.AlterModelTable(
            name='prescriptionlabtest',
            table='prescription_lab_test',
        ),
        migrations.AlterModelTable(
            name='prescriptionmedicine',
            table='prescription_medicine',
        ),
    ]
