# Generated by Django 4.2.5 on 2023-09-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_alter_labtest_table_alter_medicineschedule_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='frequency',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
