# Generated by Django 4.2.6 on 2023-11-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('prescription', '0003_rename_doctor_name_prescription_doctor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_lab', to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicines', to='prescription.prescription'),
        ),
    ]
