# Generated by Django 4.2.5 on 2023-09-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_prescriptionmedicine_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='oe',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pmh',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='tl',
        ),
    ]
