# Generated by Django 4.2.6 on 2023-12-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_alter_labtestprescription_lab_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineprescription',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescription', to='prescription.prescriptionformedicine'),
        ),
    ]
