# Generated by Django 4.2.6 on 2023-11-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('prescription', '0004_alter_prescriptionmedicine_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='lab_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_lab', to='prescription.labtest'),
        ),
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_lab', to='prescription.prescription'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicine', to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicine', to='prescription.prescription'),
        ),
    ]
