# Generated by Django 4.2.6 on 2023-11-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_alter_prescriptionlabtest_lab_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='lab_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medicine', to='prescription.labtest'),
        ),
    ]
