# Generated by Django 4.2.5 on 2023-09-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_remove_labtest_created_at_remove_labtest_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlabtest',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription'),
        ),
    ]
