# Generated by Django 4.2.6 on 2023-12-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('prescription', '0008_alter_medicineprescription_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineprescription',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_model', to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescription', to='prescription.prescriptionformedicine'),
        ),
    ]
