# Generated by Django 4.2.6 on 2023-12-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0010_alter_medicineprescription_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineprescription',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_for_medicine', to='prescription.prescriptionformedicine'),
        ),
    ]
