# Generated by Django 4.2.6 on 2023-12-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0013_alter_medicineprescription_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicineprescription',
            table='medicine_prescription',
        ),
    ]
