# Generated by Django 4.2.6 on 2023-10-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('patient', '0005_alter_patient_profile_table_delete_appointment_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('is_confirmed', models.BooleanField(default=False, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to='user.user')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to='patient.patient_profile')),
            ],
            options={
                'db_table': 'patient_appointment',
            },
        ),
    ]
