# Generated by Django 5.0 on 2023-12-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getappointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to='doctor.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='getappointment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_appointments', to='patient.patientprofile'),
            preserve_default=False,
        ),
    ]
