# Generated by Django 4.2.5 on 2023-09-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_alter_day_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='day',
            table='day',
        ),
    ]
