# Generated by Django 4.2.5 on 2023-09-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0003_alter_day_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='day',
            table='days',
        ),
    ]
