# Generated by Django 4.2.3 on 2023-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='hours',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='procedures',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='treatments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
