# Generated by Django 4.1.7 on 2023-06-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgansProblemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255)),
                ('problem_specification', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('organ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.organ')),
            ],
        ),
        migrations.RemoveField(
            model_name='problemspecification',
            name='organ_problem',
        ),
        migrations.RemoveField(
            model_name='departmentspecification',
            name='problem_specification',
        ),
        migrations.DeleteModel(
            name='OrgansProblem',
        ),
        migrations.DeleteModel(
            name='ProblemSpecification',
        ),
        migrations.AddField(
            model_name='departmentspecification',
            name='organ_problem_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_problem_specification', to='adminpanel.organsproblemspecification'),
        ),
    ]
