# Generated by Django 4.2.1 on 2023-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('patient', 'patient')], default='doctor', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
