# Generated by Django 4.2.3 on 2023-07-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varifyotp',
            old_name='user_id',
            new_name='user',
        ),
    ]
