# Generated by Django 4.2.1 on 2023-07-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_userprofile_role_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='doctor', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
