# Generated by Django 4.1.7 on 2023-07-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_awards_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='adminpanel.doctor_profile'),
        ),
        migrations.AlterField(
            model_name='services',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='adminpanel.doctor_profile'),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='adminpanel.doctor_profile'),
        ),
    ]
