# Generated by Django 4.1.7 on 2023-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adminpanel', '0003_remove_social_media_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentaddress',
            name='permanent_postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presentaddress',
            name='present_postal_code',
            field=models.IntegerField(max_length=255),
        ),
    ]
