# Generated by Django 4.1.7 on 2023-06-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('adminpanel', '0004_alter_permanentaddress_permanent_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='blood_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors',
                                    to='adminpanel.blood_group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors',
                                    to='adminpanel.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors',
                                    to='adminpanel.gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='matrimony',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors',
                                    to='adminpanel.matrimony'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='religion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors',
                                    to='adminpanel.religion'),
            preserve_default=False,
        ),
    ]
