# Generated by Django 4.1.7 on 2023-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('adminpanel', '0005_alter_doctor_profile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentaddress',
            name='present_postal_code',
            field=models.IntegerField(),
        ),
    ]
