# Generated by Django 4.2.3 on 2023-07-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varifyotp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varify_otp', to='adminpanel.user'),
        ),
    ]
