# Generated by Django 4.2.5 on 2023-09-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('personal_data', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nid_no', models.CharField(max_length=255, null=True)),
                ('phone_no', models.CharField(max_length=110, null=True)),
                ('experience', models.CharField(max_length=255, null=True)),
                ('biography', models.CharField(max_length=255, null=True)),
                ('languages_spoken', models.CharField(max_length=255, null=True)),
                ('passport_no', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.blood_group')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='department.department')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.gender')),
                ('matrimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.matrimony')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.religion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='user.user')),
            ],
            options={
                'db_table': 'doctor_profile',
            },
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='doctor.doctor_profile')),
            ],
            options={
                'db_table': 'doctor_social_media',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatments', models.CharField(max_length=255, null=True)),
                ('procedures', models.CharField(max_length=255, null=True)),
                ('hours', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctor.doctor_profile')),
            ],
            options={
                'db_table': 'doctor_services',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('passing_year', models.DateField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationID', to='personal_data.board')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='doctor.doctor_profile')),
            ],
            options={
                'db_table': 'doctor_educations',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_and_honors', models.CharField(max_length=255, null=True)),
                ('publications', models.CharField(max_length=255, null=True)),
                ('memberships', models.CharField(max_length=255, null=True)),
                ('board_certification_number', models.CharField(max_length=255, null=True)),
                ('research_interests', models.CharField(max_length=255, null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='doctor.doctor_profile')),
            ],
            options={
                'db_table': 'doctor_awards',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_availability', models.CharField(max_length=255, null=True)),
                ('accepting_new_patients', models.CharField(max_length=255, null=True)),
                ('average_wait_time', models.CharField(max_length=255, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('available_facilities', models.CharField(max_length=255, null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='doctor.doctor_profile')),
            ],
            options={
                'db_table': 'doctor_availability',
            },
        ),
    ]
