<<<<<<< HEAD
# Generated by Django 5.0 on 2023-12-14 17:04
=======
# Generated by Django 5.0 on 2023-12-27 07:21
>>>>>>> 0a0d8f532772ef8919a2217788d4c6179800016c

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('personal_data', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('birth_registration_no', models.CharField(max_length=255, null=True)),
                ('phone_no', models.CharField(max_length=110, null=True)),
                ('nid_no', models.CharField(max_length=20, null=True)),
                ('experience', models.CharField(max_length=1000, null=True)),
                ('biography', models.CharField(max_length=1000, null=True)),
                ('languages_spoken', models.CharField(max_length=255, null=True)),
                ('passport_no', models.CharField(max_length=255, null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.blood_group')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='department.department')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.gender')),
                ('matrimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.matrimony')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.religion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='user.user')),
            ],
            options={
                'db_table': 'doctor_profile',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('awards', models.CharField(max_length=255, null=True)),
                ('honors', models.CharField(max_length=255, null=True)),
                ('publications', models.CharField(max_length=255, null=True)),
                ('research_interests', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_awards', to='user.user')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_awards', to='user.user')),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='doctor.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_awards',
            },
        ),
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('per_patient_time', models.IntegerField(null=True)),
                ('consultation_fee', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_appointment', to='user.user')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_appointment', to='user.user')),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_schedules', to='doctor.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_appointment_schedule',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('certificate_degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('result', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('passing_year', models.DateField()),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educationID', to='personal_data.board')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='doctor.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_educations',
            },
        ),
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_off_day', to='user.user')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to='doctor.doctorprofile')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_off_day', to='user.user')),
                ('off_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day_name', to='personal_data.day')),
            ],
            options={
                'db_table': 'doctor_off_day',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('appointment_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_time', to='doctor.appointmentschedule')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_time', to='doctor.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_schedule_times',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('website', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='doctor.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_social_media',
            },
        ),
    ]
