# Generated by Django 4.2.5 on 2023-09-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='board_certification_number',
            new_name='professional_achievement',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='memberships',
        ),
    ]
