# Generated by Django 5.0 on 2024-01-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='biography',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
