# Generated by Django 4.2.6 on 2023-11-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offday',
            table='doctor_off_day',
        ),
    ]
