# Generated by Django 5.0 on 2024-01-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_chamber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber',
            old_name='phone_no',
            new_name='hospital_phone_no',
        ),
    ]
