# Generated by Django 4.2.5 on 2023-09-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_board_certification_number_awards_professional_achievement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='research_interests',
            new_name='research_interest',
        ),
    ]
