# Generated by Django 4.2.5 on 2023-09-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_research_interests_awards_research_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='awards_and_honors',
            new_name='awards',
        ),
        migrations.RenameField(
            model_name='awards',
            old_name='professional_achievement',
            new_name='honors',
        ),
    ]
