# Generated by Django 4.2.5 on 2023-09-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_awards_and_honors_awards_awards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='honors',
            new_name='honor',
        ),
        migrations.RenameField(
            model_name='awards',
            old_name='publications',
            new_name='publication',
        ),
    ]
