# Generated by Django 4.2.5 on 2023-09-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
        ('doctor', '0005_rename_honors_awards_honor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educationID', to='personal_data.board'),
        ),
    ]
