# Generated by Django 4.2.5 on 2023-09-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_education_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='honor',
            new_name='honors',
        ),
        migrations.RenameField(
            model_name='awards',
            old_name='publication',
            new_name='publications',
        ),
        migrations.RenameField(
            model_name='awards',
            old_name='research_interest',
            new_name='research_interests',
        ),
    ]
