# Generated by Django 4.2.5 on 2023-09-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_rename_honor_awards_honors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletime',
            name='appointment_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_time', to='doctor.appointmentschedule'),
        ),
    ]
