# Generated by Django 4.2.5 on 2023-09-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_offday_appointment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='birth_registration_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='nid_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
