# Generated by Django 4.2.5 on 2023-09-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctor_profile_birth_registration_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Media',
            new_name='SocialMedia',
        ),
    ]
