# Generated by Django 4.2.5 on 2023-09-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_scheduletime_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_schedules', to='doctor.doctor_profile'),
        ),
    ]
