# Generated by Django 4.2.5 on 2023-09-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_appointmentschedule_doctor_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentschedule',
            table='doctor_appointment_schedule',
        ),
    ]
