# Generated by Django 4.2.5 on 2023-09-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_appointmentschedule_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointmentschedule',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='modified_by',
        ),
    ]
