# Generated by Django 4.2.5 on 2023-09-22 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('doctor', '0015_remove_appointmentschedule_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_appointment', to='user.user'),
        ),
        migrations.AddField(
            model_name='appointmentschedule',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_appointment', to='user.user'),
        ),
    ]
