# Generated by Django 4.2.5 on 2023-09-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_remove_awards_created_by_remove_awards_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletime',
            name='appointment_schedule',
        ),
    ]
