# Generated by Django 4.2.5 on 2023-09-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('doctor', '0020_scheduletime_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_appointment', to='user.user'),
        ),
        migrations.AddField(
            model_name='appointmentschedule',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_appointment', to='user.user'),
        ),
        migrations.AddField(
            model_name='awards',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_awards', to='user.user'),
        ),
        migrations.AddField(
            model_name='awards',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_awards', to='user.user'),
        ),
        migrations.AddField(
            model_name='offday',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_off_day', to='user.user'),
        ),
        migrations.AddField(
            model_name='offday',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_off_day', to='user.user'),
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_schedule_time', to='user.user'),
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_schedule_time', to='user.user'),
        ),
    ]
