# Generated by Django 4.2.5 on 2023-09-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_remove_scheduletime_doctor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_profile'),
        ),
    ]
