# Generated by Django 4.2.5 on 2023-09-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_alter_appointmentschedule_doctor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletime',
            name='appointment_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='doctor.appointmentschedule'),
        ),
        migrations.AlterModelTable(
            name='scheduletime',
            table='schedule_times',
        ),
    ]
