# Generated by Django 4.2.5 on 2023-09-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_scheduletime_appointment_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletime',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='modified_by',
        ),
        migrations.AlterModelTable(
            name='scheduletime',
            table='doctor_schedule_times',
        ),
    ]
