# Generated by Django 4.2.5 on 2023-09-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_alter_day_table'),
        ('doctor', '0031_alter_scheduletime_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offday',
            name='appointment_schedule',
        ),
        migrations.AlterField(
            model_name='offday',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day_doctor_profile', to='doctor.doctor_profile'),
        ),
        migrations.AlterField(
            model_name='offday',
            name='off_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to='personal_data.day'),
        ),
    ]
