# Generated by Django 4.2.5 on 2023-09-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0003_alter_day_table'),
        ('doctor', '0032_remove_offday_appointment_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offday',
            name='appointment_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day', to='doctor.appointmentschedule'),
        ),
        migrations.AlterField(
            model_name='offday',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day', to='doctor.doctor_profile'),
        ),
        migrations.AlterField(
            model_name='offday',
            name='off_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day', to='personal_data.day'),
        ),
    ]
