# Generated by Django 4.2.5 on 2023-09-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_offday_appointment_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offday',
            name='appointment_schedule',
        ),
        migrations.AlterField(
            model_name='offday',
            name='doctor_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day_doctor_profile', to='doctor.doctor_profile'),
        ),
    ]
