# Generated by Django 4.2.5 on 2023-09-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_offday_appointment_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offday',
            name='appointment_schedule',
        ),
    ]
