# Generated by Django 4.2.5 on 2023-09-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_remove_offday_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='offday',
            name='appointment_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day', to='doctor.appointmentschedule'),
        ),
    ]
