# Generated by Django 4.2.5 on 2023-09-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0004_alter_day_table'),
        ('doctor', '0037_offday_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offday',
            name='appointment_schedule',
        ),
        migrations.AlterField(
            model_name='offday',
            name='doctor_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to='doctor.doctor_profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offday',
            name='off_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_day_name', to='personal_data.day'),
        ),
    ]
