# Generated by Django 4.2.5 on 2023-09-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
