# Generated by Django 4.2.5 on 2023-09-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organ_problem_speci', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmentID', to='department.department')),
                ('organ_problem_specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_problem_specificationID', to='organ_problem_speci.organsproblemspecification')),
            ],
            options={
                'db_table': 'department_speci',
            },
        ),
    ]
