# Generated by Django 5.0 on 2023-12-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash',
        ),
    ]
