# Generated by Django 4.1.7 on 2023-06-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgansProbleam',
            new_name='OrgansProblem',
        ),
    ]
