# Generated by Django 4.1.7 on 2023-06-09 15:17

from django.db import migrations, models
import django.db.models.deletion
import myadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemspecification',
            name='organ',
        ),
        migrations.AddField(
            model_name='problemspecification',
            name='organ_problem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_problem', to='myadmin.organsproblem'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=myadmin.models.article_filepath),
        ),
    ]
