# Generated by Django 4.1.7 on 2023-06-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_remove_problemspecification_organ_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemspecification',
            old_name='organ_problem_id',
            new_name='organ_problem',
        ),
    ]
