# Generated by Django 4.1.7 on 2023-06-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_rename_organ_problem_id_problemspecification_organ_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='heading',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(max_length=1000),
        ),
    ]
