# Generated by Django 4.1.7 on 2023-06-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_alter_article_description_alter_article_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='body_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_part_id', to='myadmin.bodypart'),
        ),
        migrations.AlterField(
            model_name='organsproblem',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_id', to='myadmin.organ'),
        ),
    ]
