# Generated by Django 4.1.7 on 2023-06-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_alter_organ_body_part_alter_organsproblem_organ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='body_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.bodypart'),
        ),
        migrations.AlterField(
            model_name='organsproblem',
            name='organ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.organ'),
        ),
    ]
