# Generated by Django 4.2.4 on 2023-08-15 15:26

import adminpanel.doctor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('personal_data', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('nid_no', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=110)),
                ('experience', models.CharField(max_length=255, null=True)),
                ('biography', models.CharField(max_length=255, null=True)),
                ('languages_spoken', models.CharField(max_length=255)),
                ('passport_no', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.blood_group')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='department.department')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.gender')),
                ('matrimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.matrimony')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='personal_data.religion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='doctor.doctor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatments', models.CharField(max_length=255, null=True)),
                ('procedures', models.CharField(max_length=255, null=True)),
                ('hours', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctor.doctor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='PresentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_village_state', models.CharField(max_length=255)),
                ('present_postal_code', models.IntegerField()),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='present_addresses', to='doctor.doctor_profile')),
                ('present_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_district', to='personal_data.district')),
                ('present_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_division', to='personal_data.division')),
                ('present_upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_upazila', to='personal_data.upazila')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_village_state', models.CharField(max_length=255)),
                ('permanent_postal_code', models.IntegerField()),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_addresses', to='doctor.doctor_profile')),
                ('permanent_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_district', to='personal_data.district')),
                ('permanent_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_division', to='personal_data.division')),
                ('permanent_upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_upazila', to='personal_data.upazila')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_photos', models.ImageField(null=True, upload_to=adminpanel.doctor.models.doctor_filepath)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doctor.doctor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('passing_year', models.DateField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationID', to='doctor.board')),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='doctor.doctor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_and_honors', models.CharField(max_length=255, null=True)),
                ('publications', models.CharField(max_length=255, null=True)),
                ('memberships', models.CharField(max_length=255, null=True)),
                ('board_certification_number', models.CharField(max_length=255, null=True)),
                ('research_interests', models.CharField(max_length=255, null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='doctor.doctor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_availability', models.CharField(max_length=255, null=True)),
                ('accepting_new_patients', models.CharField(max_length=255, null=True)),
                ('average_wait_time', models.CharField(max_length=255, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('available_facilities', models.CharField(max_length=255, null=True)),
                ('doctor_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='doctor.doctor_profile')),
            ],
        ),
    ]
