# Generated by Django 4.2.4 on 2023-08-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_board'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='languages_spoken',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='nid_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='phone_no',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationID', to='personal_data.board'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
